# Generated by Django 4.1.4 on 2022-12-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='content',
        ),
        migrations.AddField(
            model_name='drink',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='drink',
            name='pump',
            field=models.IntegerField(default=0),
        ),
    ]
