# Generated by Django 4.1.4 on 2023-01-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_drink_content_drink_photo_drink_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(height_field=400, null=True, upload_to='uploads/', width_field=400),
        ),
        migrations.AlterField(
            model_name='drink',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('password', models.IntegerField(default=4324)),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.drink', verbose_name='Drink')),
            ],
        ),
    ]
